# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers :
        default :
            web_path:
                # use %kernel.project_dir%/web for Symfony prior to 4.0.0
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/"

    cache: default
    filter_sets :
        # the name of the "filter set"
        my_thumb :
            # adjust the image quality to 75%
            quality : 75

            # list of transformations to apply (the "filters")
            filters :

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [528, 396], mode : outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background : { size : [546, 414], position : center, color : '#000000' }















    <div class="row">
        {% for annonce in annonces %}
        <div class="col 4">
            <div class="card">

                <div class="card-image">

                    <img src="{{ asset('images/'~annonce.zip) | imagine_filter('my_thumb')}}">
                    <span class="card-title">{{annonce.title}} ({{ annonce.price }} â‚¬)</span>

                </div>
                <div class="card-content">
                    <p>{{ annonce.description }}</p>
                </div>
                <div class="card-action">
                    <a href="">Consulter</a>
                </div>



            </div>
        </div>
        {% endfor %}
    </div>